//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public System.Guid InvoiceId { get; set; }
        public string Consecutive { get; set; }
        public decimal Total { get; set; }
        public System.Guid ItemId { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
